apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arcadia-app2
  name: arcadia-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-app2
  template:
    metadata:
      labels:
        app: arcadia-app2
    spec:
      containers:
      - image: doddywid/arcadia-app2:v6
        name: arcadia-app2
        env:
        - name: arcadia_appsite
          value: "my-site-name"
        - name: arcadia_backend_proto
          value: "http://"
        - name: arcadia_backend_domain
          value: "arcadia-backend-svc:8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcadia-app2-svc
  name: arcadia-app2-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-app2
