apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arcadia-mainapp
  name: arcadia-mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-mainapp
  template:
    metadata:
      labels:
        app: arcadia-mainapp
    spec:
      containers:
      - image: doddywid/arcadia-mainapp:v6
        name: arcadia-mainapp
        env:
        - name: arcadia_appsite
          value: "mk8s_udf_cluster"
        - name: arcadia_app2_proto
          value: "http://"
        - name: arcadia_app2_domain
          value: "arcadia-app2-svc:8080"
        - name: arcadia_app3_proto
          value: "http://"
        - name: arcadia_app3_domain
          value: "arcadia-app3-svc:8080"
        - name: arcadia_backend_proto
          value: "http://"
        - name: arcadia_backend_domain
          value: "arcadia-backend-svc:8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcadia-mainapp-svc
  name: arcadia-mainapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-mainapp
